"""VisualSpec v1: portable, dependency-free renderer and delivery contract.

This is the canonical source. Backend copies are generated by
scripts/sync_visual_contract.py; do not change a vendored copy independently.
"""

from __future__ import annotations

import copy
import json
import math
from collections import Counter
from typing import Any
from urllib.parse import urlsplit

VISUAL_CONTRACT_VERSION = "1"
MAX_VISUAL_BYTES = 2_000_000
MAX_VISUALS = 64
MAX_POINTS = 10_000

# Examples describe the common subset supported by local, Web and Desktop UIs.
_CATALOG = {
    "timeseries": (
        "Changes over time; include time and quantity units",
        {
            "x_label": "Time",
            "x_unit": "h",
            "y_label": "Population",
            "y_unit": "CFU",
            "series": [{"name": "Population", "points": [[0, 1], [1, 2]]}],
        },
    ),
    "bar": (
        "Compare categories, endpoint counts or scenario summaries",
        {"items": [{"label": "Control", "value": 12, "unit": "CFU"}]},
    ),
    "scatter": (
        "Compare measurements, predictions, residuals or uncertainty",
        {
            "x_label": "Observed",
            "y_label": "Predicted",
            "x_unit": "CFU",
            "y_unit": "CFU",
            "points": [{"x": 12, "y": 13, "label": "Plate 1"}],
        },
    ),
    "heatmap": (
        "Matrices, spatial fields, correlations or parameter sweeps",
        {
            "x_labels": ["A", "B"],
            "y_labels": ["Control"],
            "values": [[1, 2]],
            "unit": "CFU",
        },
    ),
    "graph": (
        "Measured or modeled networks and dependencies",
        {
            "nodes": [{"id": "A"}, {"id": "B"}],
            "edges": [{"source": "A", "target": "B"}],
        },
    ),
    "table": (
        "Exact values and metadata; accompany a plot when one aids interpretation",
        {"columns": ["Plate", "Count (CFU)"], "rows": [["A", 12]]},
    ),
    "image": (
        "Scientific images, annotations, segmentation masks and overlays",
        {
            "source": {"kind": "artifact", "path": "outputs/annotated.png"},
            "alt": "Detected colonies with numbered bounding boxes",
            "caption": "Computed detections; inspect low-confidence regions.",
        },
    ),
    "structure3d": (
        "Molecular or structural coordinates (PDB/mmCIF common subset)",
        {
            "format": "pdb",
            "source": {"kind": "artifact", "path": "outputs/structure.pdb"},
        },
    ),
    "text": (
        "Interpretation, caveats, abstentions or a result with no numeric plot",
        {"text": "Interpret the computed result within its declared intended use."},
    ),
}
SUPPORTED_RENDERERS = tuple(_CATALOG)
VISUALIZATION_AGENT_GUIDANCE = (
    "Almost every new Lab and scientific result model needs a useful visualization of actual "
    "computed outputs. Available renderers: timeseries (time evolution), bar (categories), "
    "scatter (observed versus predicted), heatmap (matrices/spatial fields), graph (networks), "
    "table (exact values), image (scientific images/overlays), structure3d (coordinates), and "
    "text (interpretation/caveats). Choose by the user's question; a table is not the default "
    "for every result. Before authoring, read get_biosimulant_authoring_contract topic "
    "visualization. Record visuals in MRS/MTS, implement BioModule.visualize() from computed "
    "state and declare lab.yaml visualization requirements. Infrastructure-only components "
    "may opt out with a recorded reason. Ad-hoc chat charts do not satisfy reusable Lab "
    "visualization requirements. Retain typed scientific outputs alongside visuals."
)


def visualization_catalog() -> dict[str, Any]:
    return {
        "schema_version": VISUAL_CONTRACT_VERSION,
        "limits": {
            "visual_bytes": MAX_VISUAL_BYTES,
            "visuals": MAX_VISUALS,
            "points": MAX_POINTS,
        },
        "renderers": {
            kind: {
                "use_when": purpose,
                "example": {
                    "schema_version": "1",
                    "render": kind,
                    "data": copy.deepcopy(data),
                },
                "clients": ["local", "web", "desktop"],
            }
            for kind, (purpose, data) in _CATALOG.items()
        },
        "custom_renderers": "Unsupported unless a renderer is registered in every target client; v1 uses the nine portable kinds.",
    }


def _number(value: Any) -> bool:
    try:
        return type(value) in (int, float) and math.isfinite(value)
    except OverflowError:
        return False


def _string(value: Any) -> bool:
    return isinstance(value, str) and bool(value.strip())


def _list(value: Any) -> bool:
    return isinstance(value, list) and 0 < len(value) <= MAX_POINTS


def _safe_url(value: Any, *, image: bool = False) -> bool:
    if not _string(value):
        return False
    if image and value.startswith("data:image/"):
        return ";base64," in value or value.startswith("data:image/svg+xml,")
    if value.startswith("/api/"):
        return True
    try:
        parsed = urlsplit(value)
    except ValueError:
        return False
    return parsed.scheme in {"http", "https"} and bool(parsed.netloc)


def _source(value: Any, *, image: bool = False) -> bool:
    if not isinstance(value, dict):
        return False
    if value.get("kind") == "artifact":
        return (
            ("artifact_id" not in value or _string(value["artifact_id"]))
            and ("path" not in value or _string(value["path"]))
            and (_string(value.get("artifact_id")) or _string(value.get("path")))
        )
    if value.get("kind") == "url":
        return _safe_url(value.get("url"), image=image)
    return False


def validate_payload(spec: Any) -> str | None:
    """Validate portable v1, even if a legacy visual omits schema_version."""
    if not isinstance(spec, dict) or spec.get("schema_version", "1") != "1":
        return "VisualSpec schema_version must be '1'"
    kind, data = spec.get("render"), spec.get("data")
    if kind not in SUPPORTED_RENDERERS or not isinstance(data, dict):
        return "Expected a supported render and a data mapping"
    if "description" in spec and not isinstance(spec["description"], str):
        return "description must be a string"
    try:
        encoded = json.dumps(spec, allow_nan=False).encode()
    except (TypeError, ValueError, OverflowError, RecursionError):
        return "VisualSpec must contain finite JSON values"
    if len(encoded) > MAX_VISUAL_BYTES:
        return "VisualSpec exceeds 2 MB; use a retained artifact or bounded preview"
    valid = False
    if kind == "timeseries":
        series = data.get("series")
        valid = _list(series) and all(
            isinstance(s, dict)
            and _list(s.get("points"))
            and all(
                isinstance(p, list) and len(p) == 2 and all(_number(v) for v in p)
                for p in s["points"]
            )
            for s in series
        )
    elif kind == "bar":
        items = data.get("items", data.get("bars"))
        valid = _list(items) and all(
            isinstance(i, dict) and _string(i.get("label")) and _number(i.get("value"))
            for i in items
        )
    elif kind == "scatter":
        points = data.get("points")
        valid = _list(points) and all(
            isinstance(p, dict) and _number(p.get("x")) and _number(p.get("y"))
            for p in points
        )
    elif kind == "heatmap":
        rows = data.get("values", data.get("matrix"))
        valid = (
            _list(rows)
            and _list(rows[0])
            and len(rows) * len(rows[0]) <= MAX_POINTS
            and all(
                isinstance(row, list)
                and len(row) == len(rows[0])
                and all(_number(v) for v in row)
                for row in rows
            )
        )
        if valid:
            valid = all(
                key not in data
                or isinstance(data[key], list)
                and len(data[key]) == n
                and all(isinstance(label, str) for label in data[key])
                for key, n in (("x_labels", len(rows[0])), ("y_labels", len(rows)))
            )
    elif kind == "table":
        cols, rows = data.get("columns"), data.get("rows")
        valid = (
            _list(cols)
            and all(_string(c) for c in cols)
            and len(set(cols)) == len(cols)
            and _list(rows)
            and all(isinstance(row, list) and len(row) == len(cols) for row in rows)
        )
    elif kind == "graph":
        nodes, edges = data.get("nodes"), data.get("edges", [])
        if _list(nodes) and all(
            isinstance(n, dict) and _string(n.get("id")) for n in nodes
        ):
            ids = {n["id"] for n in nodes}
            valid = (
                len(ids) == len(nodes)
                and isinstance(edges, list)
                and len(edges) <= MAX_POINTS
                and all(
                    isinstance(e, dict)
                    and _string(e.get("source"))
                    and _string(e.get("target"))
                    and e["source"] in ids
                    and e["target"] in ids
                    for e in edges
                )
            )
    elif kind == "image":
        valid = _source(data.get("source"), image=True) or _safe_url(
            data.get("src", data.get("url")), image=True
        )
        valid = valid and _string(data.get("alt"))
    elif kind == "structure3d":
        valid = data.get("format") in ("pdb", "mmcif", "cif") and _source(
            data.get("source")
        )
    elif kind == "text":
        valid = _string(data.get("text", data.get("markdown")))
    return (
        None
        if valid
        else f"Invalid or empty {kind} payload; follow the visualization catalog example"
    )


def validate_requirements(value: Any) -> list[str]:
    if value is None:
        return []
    if not isinstance(value, dict) or value.get("schema_version") != "1":
        return ["visualization.schema_version must be '1'"]
    required = value.get("required", [])
    if not isinstance(required, list) or len(required) > MAX_VISUALS:
        return ["visualization.required must be a list of at most 64 requirements"]
    errors = []
    for item in required:
        if (
            not isinstance(item, dict)
            or not _string(item.get("module"))
            or item.get("render") not in SUPPORTED_RENDERERS
            or type(item.get("min_count", 1)) is not int
            or not 1 <= item.get("min_count", 1) <= MAX_VISUALS
        ):
            errors.append(
                "Each requirement needs module alias, supported render and min_count 1..64"
            )
    if not required and not _string(value.get("opt_out_reason")):
        errors.append(
            "Declare at least one required visual or a nonempty opt_out_reason"
        )
    if required and value.get("opt_out_reason"):
        errors.append("required visuals and opt_out_reason are mutually exclusive")
    return errors


def audit_visualizations(
    visuals: Any, requirements: Any = None, *, diagnostics: Any = None
) -> dict[str, Any]:
    """Validate actual output and match requirements; never discard scientific data."""
    issues = []
    counts: Counter[tuple[str, str]] = Counter()
    groups = visuals if isinstance(visuals, list) else []
    if not isinstance(visuals, list):
        issues.append({"code": "invalid_visuals", "message": "visuals must be a list"})
    total = 0
    for group in groups:
        if (
            not isinstance(group, dict)
            or not _string(group.get("module"))
            or not isinstance(group.get("visuals"), list)
        ):
            issues.append(
                {"code": "invalid_group", "message": "Expected module and visuals list"}
            )
            continue
        for index, spec in enumerate(group["visuals"]):
            total += 1
            error = validate_payload(spec)
            if error:
                issues.append(
                    {
                        "code": "invalid_visual",
                        "module": group["module"],
                        "index": index,
                        "message": error,
                    }
                )
            else:
                counts[(group["module"], spec["render"])] += 1
    if total > MAX_VISUALS:
        issues.append({"code": "visual_limit", "message": "At most 64 visuals per Lab"})
    if isinstance(diagnostics, list):
        issues.extend(diagnostics[:MAX_VISUALS])
    errors = validate_requirements(requirements)
    issues.extend({"code": "invalid_requirements", "message": e} for e in errors)
    checks = []
    if requirements is not None and not errors:
        for item in requirements.get("required", []):
            count = counts[(item["module"], item["render"])]
            checks.append(
                {
                    "module": item["module"],
                    "render": item["render"],
                    "expected_count": item.get("min_count", 1),
                    "observed_count": count,
                    "status": "passed"
                    if count >= item.get("min_count", 1)
                    else "failed",
                }
            )
    failed = errors or any(c["status"] == "failed" for c in checks)
    # Declared delivery requires the whole visual set to conform, not just one good spec.
    status = (
        "not_declared"
        if requirements is None
        else "failed"
        if failed or issues
        else "passed"
    )
    return {
        "schema_version": "1",
        "status": status,
        "valid_count": sum(counts.values()),
        "checks": checks,
        "diagnostics": issues[:MAX_VISUALS],
        "diagnostics_count": len(issues),
    }


def visual_spec_schema() -> dict[str, Any]:
    """JSON Schema for discovery/tooling; semantic checks additionally check IDs,
    rectangular matrices, table widths, finite JSON and payload byte limits.
    """
    string = {"type": "string", "minLength": 1}
    number = {"type": "number"}

    def array(items: dict[str, Any], *, empty: bool = False) -> dict[str, Any]:
        return {
            "type": "array",
            "minItems": 0 if empty else 1,
            "maxItems": MAX_POINTS,
            "items": items,
        }

    def obj(properties: dict[str, Any], required: list[str]) -> dict[str, Any]:
        return {"type": "object", "properties": properties, "required": required}

    artifact = obj(
        {"kind": {"const": "artifact"}, "artifact_id": string, "path": string}, ["kind"]
    )
    artifact["anyOf"] = [{"required": ["artifact_id"]}, {"required": ["path"]}]
    source = {
        "oneOf": [
            artifact,
            obj({"kind": {"const": "url"}, "url": string}, ["kind", "url"]),
        ]
    }
    point = {"type": "array", "minItems": 2, "maxItems": 2, "items": number}
    schemas = {
        "timeseries": obj(
            {
                "series": array(
                    obj({"name": string, "points": array(point)}, ["points"])
                )
            },
            ["series"],
        ),
        "bar": obj(
            {
                "items": array(
                    obj(
                        {"label": string, "value": number, "unit": string},
                        ["label", "value"],
                    )
                )
            },
            ["items"],
        ),
        "scatter": obj(
            {
                "points": array(
                    obj({"x": number, "y": number, "label": string}, ["x", "y"])
                )
            },
            ["points"],
        ),
        "heatmap": obj(
            {
                "values": array(array(number)),
                "x_labels": array(string),
                "y_labels": array(string),
            },
            ["values"],
        ),
        "graph": obj(
            {
                "nodes": array(obj({"id": string}, ["id"])),
                "edges": array(
                    obj({"source": string, "target": string}, ["source", "target"]),
                    empty=True,
                ),
            },
            ["nodes"],
        ),
        "table": obj(
            {"columns": array(string), "rows": array({"type": "array", "items": {}})},
            ["columns", "rows"],
        ),
        "image": obj(
            {"source": {"oneOf": source["oneOf"][:2]}, "src": string, "alt": string},
            ["alt"],
        ),
        "structure3d": obj(
            {"source": source, "format": {"enum": ["pdb", "mmcif", "cif"]}},
            ["source", "format"],
        ),
        "text": obj({"text": string}, ["text"]),
    }
    schemas["image"]["anyOf"] = [{"required": ["source"]}, {"required": ["src"]}]
    # Supported legacy aliases in the validator are also discoverable here.
    for kind, alias, canonical in (
        ("bar", "bars", "items"),
        ("heatmap", "matrix", "values"),
        ("text", "markdown", "text"),
    ):
        schemas[kind]["properties"][alias] = schemas[kind]["properties"][canonical]
        schemas[kind]["required"] = []
        schemas[kind]["anyOf"] = [{"required": [canonical]}, {"required": [alias]}]
    schemas["image"]["properties"]["url"] = string
    schemas["image"]["anyOf"].append({"required": ["url"]})
    return {
        "$schema": "https://json-schema.org/draft/2020-12/schema",
        "$id": "https://docs.biosimulant.com/schemas/visual-spec-v1.json",
        "title": "Biosimulant VisualSpec v1",
        "oneOf": [
            obj(
                {
                    "schema_version": {"const": "1"},
                    "render": {"const": kind},
                    "data": schema,
                    "description": {"type": "string"},
                },
                ["schema_version", "render", "data"],
            )
            for kind, schema in schemas.items()
        ],
    }
